version: '3'
services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped

volumes:
  postgresqldata: